### PR TITLE
New icon in about section

### PR DESCRIPTION
**Pull request by ChESch**
Added new icon in about section and made it a little bit bigger

### CODE REVIEW

**Comment by ajgassner** [comment]
www/img/app-icon.png is now 1024x1024. Should be exactly the double size of the HTMl attribute. E.g. 60x60 -> 120x120 or in our case 100x100 -> 200x200. Beside the new image is wrong I think

**Comment by ChESch** [comment]
What do you mean with the icon is wrong?

**Comment by ajgassner** [comment]
https://github.com/Grisu-NOE/mobile-app/pull/103/files

Comapre the old with the new one. Where is the red background?

**Comment by ChESch** [comment]
I thought it would look nicer if you leave the Background so it doesn't mix up with iOS or Android style. Or is it possible to choose the about icon dependent on the OS?

**Comment by ajgassner** [comment]
Sure this is possible.

**Comment by ChESch** [comment]
So i think it would be nice to take to do it. Problem is I don't know how.

**Comment by ajgassner** [comment]
see https://github.com/Grisu-NOE/mobile-app/blob/master/www/js/app.js#L176

**Comment by ChESch** [comment]
Here is the old one:
old version 1 1 0

And here the new:
new version 1 2 0

Let me know if you like it.

**Comment by ajgassner** [comment]
I like the old one, because there isn't only one color on the screen. The red background looks nice.

**Comment by ChESch** [comment]
Ok, I'll think about something, but I don't think it would be ready for the 1.2.0 milestone, so I'll close this Pull Request.

**Pull request closed without merging**
